<?php

return [
    'permissions' => [
        'access.admin_dashboard' => ['label' => 'Admin Dashboard', 'description' => 'Melihat dashboard admin.'],
        'access.manager_dashboard' => ['label' => 'Dashboard Manager', 'description' => 'Melihat dashboard manager.'],
        'access.products' => ['label' => 'Produk / Menu', 'description' => 'Kelola katalog produk dan harga.'],
        'access.recipes' => ['label' => 'Resep / BOM', 'description' => 'Kelola resep dan kebutuhan bahan.'],
        'access.items' => ['label' => 'Stok Bahan', 'description' => 'Kelola item bahan baku.'],
        'access.units' => ['label' => 'Satuan', 'description' => 'Kelola satuan dan konversi.'],
        'access.expense_categories' => ['label' => 'Kategori Pengeluaran', 'description' => 'Kelola kategori pengeluaran operasional.'],
        'access.users' => ['label' => 'Pengguna & Hak Akses', 'description' => 'Kelola akun dan hak akses menu.'],
        'access.employees' => ['label' => 'Master Karyawan', 'description' => 'Kelola data karyawan.'],
        'access.attendance_shifts' => ['label' => 'Master Shift', 'description' => 'Kelola master shift kerja.'],
        'access.attendance_late_rules' => ['label' => 'Rule Keterlambatan', 'description' => 'Kelola aturan telat dan potongannya.'],
        'access.settings' => ['label' => 'Pengaturan Resto', 'description' => 'Kelola profil resto dan pengaturan umum.'],
        'access.assets' => ['label' => 'Inventaris', 'description' => 'Kelola aset inventaris.'],
        'access.asset_categories' => ['label' => 'Kategori Inventaris', 'description' => 'Kelola kategori inventaris.'],
        'access.asset_locations' => ['label' => 'Lokasi Inventaris', 'description' => 'Kelola lokasi inventaris.'],
        'access.asset_incidents' => ['label' => 'Kerusakan / Pemusnahan', 'description' => 'Catat insiden inventaris.'],
        'access.receivings' => ['label' => 'Receiving Stok', 'description' => 'Input penerimaan bahan.'],
        'access.expired' => ['label' => 'Expired Disposal', 'description' => 'Kelola bahan expired/disposal.'],
        'access.stock' => ['label' => 'Stok Saat Ini', 'description' => 'Melihat stok aktif saat ini.'],
        'access.stock_opname' => ['label' => 'Stock Opname', 'description' => 'Kelola dokumen stock opname.'],
        'access.attendance_schedules' => ['label' => 'Roster Bulanan Shift', 'description' => 'Kelola roster/jadwal kerja bulanan.'],
        'access.attendances' => ['label' => 'Absensi Karyawan', 'description' => 'Kelola absensi karyawan.'],
        'access.attendance_review' => ['label' => 'Review Wajah Absensi', 'description' => 'Meninjau hasil selfie/verifikasi wajah.'],
        'access.attendance_kiosk' => ['label' => 'Kiosk Absensi', 'description' => 'Mengakses kiosk absensi tablet.'],
        'access.leave_requests' => ['label' => 'Izin / Cuti / Sakit', 'description' => 'Kelola pengajuan izin/cuti/sakit.'],
        'access.employee_meals' => ['label' => 'Makan Karyawan', 'description' => 'Catat transaksi makan karyawan.'],
        'access.expenses' => ['label' => 'Pengeluaran Operasional', 'description' => 'Ajukan dan tinjau pengeluaran operasional.'],
        'access.petty_cash' => ['label' => 'Kas Kecil', 'description' => 'Kelola dana kas kecil dan rekonsiliasi.'],
        'access.payroll' => ['label' => 'Penggajian Petugas', 'description' => 'Kelola payroll dan slip gaji.'],
        'access.pos' => ['label' => 'POS Kasir', 'description' => 'Mengakses halaman POS kasir.'],
        'access.sales_reports' => ['label' => 'Laporan Penjualan', 'description' => 'Melihat laporan penjualan.'],
        'access.top_products_report' => ['label' => 'Top 10 Penjualan', 'description' => 'Melihat produk terlaris.'],
        'access.finance_report' => ['label' => 'Laporan Keuangan', 'description' => 'Melihat laporan keuangan.'],
        'access.attendance_report' => ['label' => 'Rekap Absensi Bulanan', 'description' => 'Melihat rekap absensi bulanan.'],
        'access.opname_variance_report' => ['label' => 'Laporan Selisih Opname', 'description' => 'Melihat selisih stock opname.'],
        'access.audit_logs' => ['label' => 'Audit Log', 'description' => 'Melihat audit log sistem.'],
        'access.profile' => ['label' => 'Ubah Password', 'description' => 'Mengubah password akun sendiri.'],
    ],

    'groups' => [
        'Dashboard' => [
            'access.admin_dashboard',
            'access.manager_dashboard',
        ],
        'Master Data' => [
            'access.products',
            'access.recipes',
            'access.items',
            'access.units',
            'access.expense_categories',
            'access.users',
            'access.employees',
            'access.attendance_shifts',
            'access.attendance_late_rules',
            'access.settings',
            'access.assets',
            'access.asset_categories',
            'access.asset_locations',
            'access.asset_incidents',
        ],
        'Operasional' => [
            'access.receivings',
            'access.expired',
            'access.stock',
            'access.stock_opname',
            'access.attendance_schedules',
            'access.attendances',
            'access.attendance_review',
            'access.attendance_kiosk',
            'access.leave_requests',
            'access.employee_meals',
            'access.expenses',
            'access.petty_cash',
            'access.payroll',
            'access.pos',
        ],
        'Laporan & Profil' => [
            'access.sales_reports',
            'access.top_products_report',
            'access.finance_report',
            'access.attendance_report',
            'access.opname_variance_report',
            'access.audit_logs',
            'access.profile',
        ],
    ],

    'defaults' => [
        'admin' => [
            'access.admin_dashboard','access.products','access.recipes','access.items','access.units','access.expense_categories','access.users','access.employees','access.attendance_shifts','access.attendance_late_rules','access.settings','access.assets','access.asset_categories','access.asset_locations','access.asset_incidents','access.receivings','access.expired','access.stock','access.stock_opname','access.attendance_schedules','access.attendances','access.attendance_review','access.attendance_kiosk','access.leave_requests','access.employee_meals','access.expenses','access.petty_cash','access.payroll','access.pos','access.sales_reports','access.top_products_report','access.finance_report','access.attendance_report','access.opname_variance_report','access.audit_logs','access.profile'
        ],
        'manager' => [
            'access.manager_dashboard','access.products','access.recipes','access.employees','access.attendance_shifts','access.attendance_late_rules','access.settings','access.assets','access.asset_categories','access.asset_locations','access.asset_incidents','access.attendance_schedules','access.attendances','access.attendance_review','access.attendance_kiosk','access.leave_requests','access.employee_meals','access.expenses','access.payroll','access.sales_reports','access.finance_report','access.attendance_report','access.opname_variance_report','access.audit_logs','access.profile'
        ],
        'cashier' => [
            'access.pos','access.attendance_kiosk','access.employee_meals','access.sales_reports','access.expenses','access.settings','access.profile'
        ],
    ],

    'route_patterns' => [
        'admin.dashboard' => 'access.admin_dashboard',
        'manager.dashboard' => 'access.manager_dashboard',
        'admin.products.*' => 'access.products',
        'manager.products.*' => 'access.products',
        'admin.recipes.*' => 'access.recipes',
        'manager.recipes.*' => 'access.recipes',
        'admin.items.*' => 'access.items',
        'admin.units.*' => 'access.units',
        'admin.expense_categories.*' => 'access.expense_categories',
        'admin.users.*' => 'access.users',
        'admin.employees.*' => 'access.employees',
        'manager.employees.*' => 'access.employees',
        'admin.attendance_shifts.*' => 'access.attendance_shifts',
        'manager.attendance_shifts.*' => 'access.attendance_shifts',
        'admin.attendance_late_rules.*' => 'access.attendance_late_rules',
        'manager.attendance_late_rules.*' => 'access.attendance_late_rules',
        'admin.settings.*' => 'access.settings',
        'manager.settings.*' => 'access.settings',
        'cashier.settings.*' => 'access.settings',
        'admin.assets.*' => 'access.assets',
        'manager.assets.*' => 'access.assets',
        'admin.asset_categories.*' => 'access.asset_categories',
        'manager.asset_categories.*' => 'access.asset_categories',
        'admin.asset_locations.*' => 'access.asset_locations',
        'manager.asset_locations.*' => 'access.asset_locations',
        'admin.asset_incidents.*' => 'access.asset_incidents',
        'manager.asset_incidents.*' => 'access.asset_incidents',
        'admin.receivings.*' => 'access.receivings',
        'admin.expired.*' => 'access.expired',
        'admin.stock.index' => 'access.stock',
        'admin.stock_opname.*' => 'access.stock_opname',
        'admin.attendance_schedules.*' => 'access.attendance_schedules',
        'manager.attendance_schedules.*' => 'access.attendance_schedules',
        'admin.attendances.index' => 'access.attendances',
        'admin.attendances.store' => 'access.attendances',
        'manager.attendances.index' => 'access.attendances',
        'manager.attendances.store' => 'access.attendances',
        'admin.attendances.review' => 'access.attendance_review',
        'admin.attendances.review_update' => 'access.attendance_review',
        'manager.attendances.review' => 'access.attendance_review',
        'manager.attendances.review_update' => 'access.attendance_review',
        'attendance.kiosk' => 'access.attendance_kiosk',
        'attendance.kiosk.store' => 'access.attendance_kiosk',
        'admin.leave_requests.*' => 'access.leave_requests',
        'manager.leave_requests.*' => 'access.leave_requests',
        'admin.employee_meals.*' => 'access.employee_meals',
        'manager.employee_meals.*' => 'access.employee_meals',
        'cashier.employee_meals.*' => 'access.employee_meals',
        'admin.expenses.*' => 'access.expenses',
        'manager.expenses.*' => 'access.expenses',
        'cashier.expenses.*' => 'access.expenses',
        'admin.petty_cash.*' => 'access.petty_cash',
        'admin.payroll.*' => 'access.payroll',
        'manager.payroll.*' => 'access.payroll',
        'cashier.pos' => 'access.pos',
        'admin.reports.sales*' => 'access.sales_reports',
        'manager.reports.sales*' => 'access.sales_reports',
        'cashier.reports.sales' => 'access.sales_reports',
        'admin.reports.top_products' => 'access.top_products_report',
        'admin.reports.finance*' => 'access.finance_report',
        'manager.reports.finance*' => 'access.finance_report',
        'admin.reports.attendance*' => 'access.attendance_report',
        'manager.reports.attendance*' => 'access.attendance_report',
        'admin.reports.opname_variance' => 'access.opname_variance_report',
        'manager.reports.opname_variance' => 'access.opname_variance_report',
        'admin.reports.audit_logs*' => 'access.audit_logs',
        'manager.reports.audit_logs' => 'access.audit_logs',
        'profile.*' => 'access.profile',
    ],
];
